### ISSUE TITLE
PHP warning in the Widgets panel with the WP Debug true

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/wp-menu-icons#248] opened 2023-06-29 09:26 UTC
### Description

If the Menu Icons plugin is installed and use, and WP_DEBUG is true, there is a warning in the Widgets page.

```
Notice: Function wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see [Debugging in WordPress](https://wordpress.org/documentation/article/debugging-in-wordpress/) for more information. (This message was added in version 5.8.0.) in /home/u213785429/domains/stefancoti.com/public_html/neve/wp-includes/functions.php on line 5865
```

### Step-by-step reproduction instructions

1. Install and activate WP Menu Icons
2. Configure one of the icons in the menu
3. Install & activate - https://wordpress.org/plugins/wp-debugging/
4. Visit the Widgets page in the Dashboard

### Screenshots, screen recording, code snippet or Help Scout ticket

![widgets-issue-menu-icons](https://github.com/Codeinwp/wp-menu-icons/assets/26867648/92892710-8210-4b44-97e8-e8315e8f137c)

Reported here: https://wordpress.org/support/topic/notice-for-enqueuing-scripts-on-widgets-page/

### Environment info

https://pastebin.com/MidDvph7

### Is the issue you are reporting a regression

No

**Comment by stefan-cotitosu** [comment] 2023-06-29 09:27
the user reported it can be fixed by removing ‘wp-editor’ from the dependencies array in /menu-icons/vendor/codeinwp/gutenberg-menu-icons/class-gutenberg-menu-icons.php on line 63

**Comment by HardeepAsrani** [comment] 2023-06-29 09:31
- https://github.com/Codeinwp/otter-blocks/blob/master/inc/class-registration.php#L198C49-L214C146
- https://github.com/Codeinwp/otter-blocks/blob/ce56737db046cb5d2bfad6af8656dec8fe1641be/src/blocks/plugins/registerPlugin.tsx#L37

How we solve in Otter

**Comment by vytisbulkevicius** [comment] 2023-07-03 08:18
We can fix this as it potentially affects every user and could cause bad experience. Also, seems to be an easy fix and we don't risk causing a regression.

**Comment by girishpanchal30** [comment] 2023-07-05 09:12
Hey @stefan-cotitosu,

I've updated the composer packages and the mentioned issue is fixed, please check with this PR - https://github.com/Codeinwp/wp-menu-icons/pull/250

Thanks

**Comment by irinelenache** [comment] 2023-07-05 09:59
@girishpanchal30 Tested and the issue is fixed now 👍

**Closed** 2023-07-07 07:27 UTC
Labels: bug
