### ISSUE TITLE
Button from notice recommending Neve has fixed width which is causing issues in other languages

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/wp-menu-icons#252] opened 2023-08-05 09:33 UTC
### Description

The notice used for recommending Neve has a button with a fixed width, which doesn't look good in different languages, other than english

### Step-by-step reproduction instructions

1. Activate the plugin
2. Create a menu with icons from the plugin
3. Check the notice recommending Neve
4. Try to change the text of the button in another language -> The button has a fixed width which doesn't accommodate longer text.
![Annotation-Annotation on 2023-08-05 at 12-26-17 png](https://github.com/Codeinwp/wp-menu-icons/assets/3266155/81addcda-953f-4b10-8e99-207af887024b)

### Screenshots, screen recording, code snippet or Help Scout ticket

https://twitter.com/marcoandrei/status/1687520466817220608?s=20

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment] 2023-08-08 04:59
@rodica-andronache I've reviewed this issue and fixed it with the attached PR https://github.com/Codeinwp/wp-menu-icons/pull/254

**Comment by irinelenache** [comment] 2023-08-08 10:21
@girishpanchal30 Tested and the issue is fixed now 👍

**Closed** 2023-08-17 21:10 UTC
Labels: bug
